version: "3.1"

# 系统重启的时候，需要开启docker: systemctl start docker
## 特别注意，up之后，django还需要执行start.sh之后才能通
volumes:  
  media_vol: # 定义数据卷同步media文件夹数据

services:
  packing_nginx:
    restart: always # docker 重启时，容器自启动
    image: nginx:latest #1.19.6
    container_name: packing_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/cert:/usr/local/nginx/cert
    dns:
      - 8.8.8.8
      - 114.114.114.114
    networks:
      - packing_net

  packing_django:
    build: ./packing
    container_name: packing_django
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes: #  是django工程目录，在start.sh、uwsgi.ini、Dockerfile里都需要统一
      - ./packing:/var/www/html/packing
      - ./packing/uwsgi:/tmp # 挂载uwsgi日志
    environment:
      - DEBUG=True
    restart: always
    tty: true
    stdin_open: true
    networks:
      - packing_net
 

networks:
  packing_net: